# tomcat配置
server:
  port: 8001
  servlet:
    path: /dev/v1.0

# spring配置
spring:
  application:
    name: dev-client
  mvc:
    throw-exception-if-no-handler-found: true
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot?characterEncoding=UTF-8&useSSL=true
    username: root
    password: root

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  # jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  # redis缓存配置
  redis:
    host: localhost
    port: 6379
    max-active: 8
    max-wait: -1
    max-idle: 500
    min-idle: 0
  mail:
    host: smtp.qq.com
    username: smalltao.liu@qq.com
    password: iwonphxskndvbjfj
    protocol: smtp
    port: 587
    default-encoding: utf-8
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# mybatis配置
mybatis:
    # 别名。可省略写mybatis的xml中的resultType的全路径
    type-aliases-package: com.core.entity
    # Mybatis扫描(配置xml模式使用)
    mapper-locations: classpath:/mybatis/*.xml

# pageHelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# eureka配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8002/eureka/